In [62]:
import pandas as pd
import warnings
warnings.simplefilter('ignore')

# %matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

# Read the CSV and Perform Basic Data Cleaning

In [63]:
df = pd.read_csv("cumulative.csv")
df = df.drop(columns=["rowid", "kepid", "kepoi_name", "kepler_name", "koi_pdisposition", "koi_score", "koi_tce_delivname"])
# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')
# Drop the null rows
df = df.dropna()
df.head()

koi_disposition  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  \
0       CONFIRMED              0              0              0              0   
1       CONFIRMED              0              0              0              0   
2  FALSE POSITIVE              0              1              0              0   
3  FALSE POSITIVE              0              1              0              0   
4       CONFIRMED              0              0              0              0   

   koi_period  koi_period_err1  koi_period_err2  koi_time0bk  \
0    9.488036     2.775000e-05    -2.775000e-05   170.538750   
1   54.418383     2.479000e-04    -2.479000e-04   162.513840   
2   19.899140     1.494000e-05    -1.494000e-05   175.850252   
3    1.736952     2.630000e-07    -2.630000e-07   170.307565   
4    2.525592     3.761000e-06    -3.761000e-06   171.595550   

   koi_time0bk_err1     ...      koi_steff_err2  koi_slogg  koi_slogg_err1  \
0          0.002160     ...               -81.0      4.467           0.064   
1          0.003520     ...               -81.0      4.467           0.064   
2          0.000581     ...              -176.0      4.544           0.044   
3          0.000115     ...              -174.0      4.564           0.053   
4          0.001130     ...              -211.0      4.438           0.070   

   koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2         ra  \
0          -0.096     0.927          0.105         -0.061  291.93423   
1          -0.096     0.927          0.105         -0.061  291.93423   
2          -0.176     0.868          0.233         -0.078  297.00482   
3          -0.168     0.791          0.201         -0.067  285.53461   
4          -0.210     1.046          0.334         -0.133  288.75488   

         dec  koi_kepmag  
0  48.141651      15.347  
1  48.141651      15.347  
2  48.134129      15.436  
3  48.285210      15.597  
4  48.226200      15.509  

[5 rows x 41 columns]

In [66]:
df_X=df.drop(columns=['koi_disposition'])

In [67]:
y=df['koi_disposition']

In [68]:
df['koi_disposition'].unique().tolist()

['CONFIRMED', 'FALSE POSITIVE', 'CANDIDATE']

In [69]:
y=df['koi_disposition'].astype('category')

In [70]:
y=y.cat.codes

In [71]:
# confirmed : 1,  false positive : 2, candidate :0

In [72]:
y

0       1
1       1
2       2
3       2
4       1
5       1
6       1
7       1
8       2
9       1
10      1
11      1
12      1
13      1
14      2
15      2
16      2
17      2
18      1
19      1
20      2
21      1
22      1
23      1
24      2
25      1
26      1
27      1
28      2
29      2
       ..
9532    2
9533    0
9535    2
9536    2
9537    2
9538    2
9539    0
9540    1
9541    2
9542    0
9543    2
9544    0
9545    2
9546    0
9548    2
9549    2
9550    0
9551    0
9552    2
9553    2
9554    2
9555    2
9556    2
9557    0
9558    0
9559    2
9560    2
9561    0
9562    2
9563    2
Length: 8744, dtype: int8

In [73]:
y=y.values.reshape(-1,1)

In [74]:
from sklearn import preprocessing
from sklearn import utils

lab_enc = preprocessing.LabelEncoder()
encoded = lab_enc.fit_transform(df['koi_disposition'])

In [75]:
print(utils.multiclass.type_of_target(encoded))

multiclass


In [76]:
print(utils.multiclass.type_of_target(df['koi_disposition']))

multiclass


In [77]:
encoded

array([1, 1, 2, ..., 0, 2, 2])

In [78]:
y=encoded.reshape(-1,1)

In [79]:
y

array([[1],
       [1],
       [2],
       ..., 
       [0],
       [2],
       [2]])

In [80]:
print(utils.multiclass.type_of_target(y))

multiclass


# Create a Train Test Split

Use `koi_disposition` for the y values

In [81]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_X, y, random_state=42)

In [82]:
X_train.head()

koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  koi_period  \
8017              0              1              1              0    0.806277   
1233              0              1              1              0    3.582077   
2592              0              0              0              0    5.060923   
4770              0              1              0              1    8.480304   
6632              0              0              0              1    4.994716   

      koi_period_err1  koi_period_err2  koi_time0bk  koi_time0bk_err1  \
8017     4.947000e-06    -4.947000e-06   131.785670          0.006720   
1233     4.318000e-06    -4.318000e-06   355.515064          0.000864   
2592     2.616000e-05    -2.616000e-05   134.473160          0.004730   
4770     3.320000e-07    -3.320000e-07   135.854534          0.000031   
6632     4.495000e-05    -4.495000e-05   136.183300          0.009500   

      koi_time0bk_err2     ...      koi_steff_err2  koi_slogg  koi_slogg_err1  \
8017         -0.006720     ...              -184.0      4.471           0.054   
1233         -0.000864     ...              -235.0      4.422           0.090   
2592         -0.004730     ...              -112.0      4.492           0.048   
4770         -0.000031     ...              -169.0      3.946           0.195   
6632         -0.009500     ...              -194.0      3.706           0.320   

      koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2         ra  \
8017          -0.229     0.996          0.324         -0.108  290.81723   
1233          -0.195     0.993          0.283         -0.131  296.07822   
2592          -0.112     0.911          0.121         -0.060  289.91742   
4770          -0.105     2.210          0.375         -0.563  298.80020   
6632          -0.080     2.830          0.458         -1.068  282.58215   

            dec  koi_kepmag  
8017  38.539120      13.614  
1233  43.136940      15.193  
2592  40.828606      13.346  
4770  46.665539       7.631  
6632  46.815510      13.352  

[5 rows x 40 columns]

In [83]:
y_train

array([[2],
       [2],
       [0],
       ..., 
       [2],
       [1],
       [2]])

In [84]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6558 entries, 8017 to 8005
Data columns (total 40 columns):
koi_fpflag_nt        6558 non-null int64
koi_fpflag_ss        6558 non-null int64
koi_fpflag_co        6558 non-null int64
koi_fpflag_ec        6558 non-null int64
koi_period           6558 non-null float64
koi_period_err1      6558 non-null float64
koi_period_err2      6558 non-null float64
koi_time0bk          6558 non-null float64
koi_time0bk_err1     6558 non-null float64
koi_time0bk_err2     6558 non-null float64
koi_impact           6558 non-null float64
koi_impact_err1      6558 non-null float64
koi_impact_err2      6558 non-null float64
koi_duration         6558 non-null float64
koi_duration_err1    6558 non-null float64
koi_duration_err2    6558 non-null float64
koi_depth            6558 non-null float64
koi_depth_err1       6558 non-null float64
koi_depth_err2       6558 non-null float64
koi_prad             6558 non-null float64
koi_prad_err1        6558 non-null flo

# Pre-processing

Scale the data using the MinMaxScaler

In [85]:
from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler().fit(X_train)
y_scaler = StandardScaler().fit(y_train)

In [86]:
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
y_train_scaled = y_scaler.transform(y_train)
y_test_scaled = y_scaler.transform(y_test)

In [87]:
from sklearn import preprocessing
from sklearn import utils

lab_enc = preprocessing.LabelEncoder()
y_train_scaled = lab_enc.fit_transform(y_train_scaled)

In [88]:
y_test_scaled=lab_enc.fit_transform(y_test_scaled)

In [89]:
print(utils.multiclass.type_of_target(y_train))

multiclass


In [90]:
print(utils.multiclass.type_of_target(y_train_scaled))

multiclass


In [91]:
print(utils.multiclass.type_of_target(y_test_scaled))

multiclass


# Train the Support Vector Machine

In [92]:
from sklearn.svm import SVC 
model = SVC(gamma='auto')
model.fit(X_train_scaled, y_train_scaled)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [93]:
print(f"Training Data Score: {model.score(X_train_scaled, y_train)}")
print(f"Testing Data Score: {model.score(X_test_scaled, y_test)}")

Training Data Score: 0.8888380603842635
Testing Data Score: 0.8796889295516926


# Hyperparameter Tuning

Use `GridSearchCV` to tune the `C` and `gamma` parameters

In [94]:
# Create the GridSearchCV model
from sklearn.svm import SVC 
model = SVC(kernel='linear')

In [95]:
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [1, 5, 10],
              'gamma': [0.0001, 0.001, 0.01]}
grid = GridSearchCV(model, param_grid, verbose=3)

In [96]:
# Train the model with GridSearch

In [97]:
grid.fit(X_train_scaled, y_train_scaled)

Fitting 3 folds for each of 9 candidates, totalling 27 fits
[CV] C=1, gamma=0.0001 ...............................................
[CV] ...... C=1, gamma=0.0001, score=0.8953382084095064, total=   0.7s
[CV] C=1, gamma=0.0001 ...............................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.8s remaining:    0.0s


[CV] ...... C=1, gamma=0.0001, score=0.8764302059496567, total=   0.6s
[CV] C=1, gamma=0.0001 ...............................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    1.6s remaining:    0.0s


[CV] ...... C=1, gamma=0.0001, score=0.8974828375286041, total=   1.2s
[CV] C=1, gamma=0.001 ................................................
[CV] ....... C=1, gamma=0.001, score=0.8953382084095064, total=   0.7s
[CV] C=1, gamma=0.001 ................................................
[CV] ....... C=1, gamma=0.001, score=0.8764302059496567, total=   0.5s
[CV] C=1, gamma=0.001 ................................................
[CV] ....... C=1, gamma=0.001, score=0.8974828375286041, total=   1.2s
[CV] C=1, gamma=0.01 .................................................
[CV] ........ C=1, gamma=0.01, score=0.8953382084095064, total=   0.6s
[CV] C=1, gamma=0.01 .................................................
[CV] ........ C=1, gamma=0.01, score=0.8764302059496567, total=   0.5s
[CV] C=1, gamma=0.01 .................................................
[CV] ........ C=1, gamma=0.01, score=0.8974828375286041, total=   1.2s
[CV] C=5, gamma=0.0001 ...............................................
[CV] .

[Parallel(n_jobs=1)]: Done  27 out of  27 | elapsed:   40.4s finished


GridSearchCV(cv=None, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [1, 5, 10], 'gamma': [0.0001, 0.001, 0.01]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=3)

In [98]:
print(grid.best_params_)

{'C': 1, 'gamma': 0.0001}


In [99]:
print(grid.best_score_)

0.889752973468
